### ISSUE TITLE
Problem with nested JSON

### ISSUE THREAD

**Issue by Jvlsc** [Rooyca/obsidian-api-request#35]
Hi!

I was testing this extensión to get some data from Github repositories, but It doesn't work.  Example:

URL: https://api.github.com/repos/Helium314/HeliBoard/commits

````
```req 
method: get
url: https://api.github.com/repos/Helium314/HeliBoard/commits 
headers: {"Content-type": "application/json; charset=UTF-8"}
show: {0} -> commit -> committer -> date
```
````

I can see the raw response, but it's not working when trying to access some properties. Could you help me?

Thanks you, I apprecciate the work on this extension.

Regards

**Comment by Rooyca** [comment]
Hello @Jvlsc,

I fix one bug and I add two more haha :smiley:, (this one was added with the latest release). Well, i think it should be working now. You can try it like this:

~~~markdown
```req 
url: https://api.github.com/repos/Helium314/HeliBoard/commits
res-type: json
show: {0} -> commit -> committer -> date
```
~~~

That would give you all the dates, if you only one the first date you could use `0`, because (apparently) `{0}` is the same as `{..}` 


Have a good one!

**Comment by Rooyca** [comment]
You can update your plugin and everything should be working :+1:

**Comment by Jvlsc** [comment]
It's woking now! 🎉

This extension has a huge potential. Thanks for the quick support!
